services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    command:
      - "--http-enabled"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.angadi.duckdns.org`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    networks:
      lan: {}

networks:
  lan:
    external: true
